In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
# GANTI PATH SESUAI FILE LO
df = pd.read_csv('/content/drive/MyDrive/KecerdasanBuatan_UAS/migraine.csv')
df.head()


Age  Duration  Frequency  Location  Character  Intensity  Nausea  Vomit  \
0   30         1          5         1          1          2       1      0   
1   50         3          5         1          1          3       1      1   
2   53         2          1         1          1          2       1      1   
3   45         3          5         1          1          3       1      0   
4   53         1          1         1          1          2       1      0   

   Phonophobia  Photophobia  ...  Vertigo  Tinnitus  Hypoacusis  Diplopia  \
0            1            1  ...        0         0           0         0   
1            1            1  ...        1         0           0         0   
2            1            1  ...        0         0           0         0   
3            1            1  ...        1         0           0         0   
4            1            1  ...        0         0           0         0   

   Defect  Ataxia  Conscience  Paresthesia  DPF                        Type  
0       0       0           0            0    0  Typical aura with migraine  
1       0       0           0            0    0  Typical aura with migraine  
2       0       0           0            0    0  Typical aura with migraine  
3       0       0           0            0    0  Typical aura with migraine  
4       0       0           0            0    1  Typical aura with migraine  

[5 rows x 24 columns]

In [ ]:
# Tentukan target
TARGET = 'Type'

X = df.drop(columns=[TARGET])
y = df[TARGET]

X.shape, y.value_counts()


((400, 23),
 Type
 Typical aura with migraine       247
 Migraine without aura             60
 Familial hemiplegic migraine      24
 Typical aura without migraine     20
 Basilar-type aura                 18
 Other                             17
 Sporadic hemiplegic migraine      14
 Name: count, dtype: int64)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Lihat mapping kelas
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
label_mapping


{'Basilar-type aura': np.int64(0),
 'Familial hemiplegic migraine': np.int64(1),
 'Migraine without aura': np.int64(2),
 'Other': np.int64(3),
 'Sporadic hemiplegic migraine': np.int64(4),
 'Typical aura with migraine': np.int64(5),
 'Typical aura without migraine': np.int64(6)}

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

X_train.shape, X_test.shape


((320, 23), (80, 23))

In [ ]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)


GaussianNB()

In [ ]:
y_pred = model.predict(X_test)


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_pred, average='weighted'))
print("F1-score :", f1_score(y_test, y_pred, average='weighted'))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy : 0.925
Precision: 0.9274321266968325
Recall   : 0.925
F1-score : 0.9223571428571429

Confusion Matrix:
[[ 3  1  0  0  0  0  0]
 [ 0  3  0  0  0  2  0]
 [ 0  0 12  0  0  0  0]
 [ 0  0  1  2  0  0  0]
 [ 0  0  0  0  2  1  0]
 [ 0  1  0  0  0 48  0]
 [ 0  0  0  0  0  0  4]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.60      0.60      0.60         5
           2       0.92      1.00      0.96        12
           3       1.00      0.67      0.80         3
           4       1.00      0.67      0.80         3
           5       0.94      0.98      0.96        49
           6       1.00      1.00      1.00         4

    accuracy                           0.93        80
   macro avg       0.92      0.81      0.85        80
weighted avg       0.93      0.93      0.92        80



In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(model, X, y_encoded, cv=cv, scoring='accuracy')

scores.mean(), scores.std()


(np.float64(0.945), np.float64(0.03999999999999999))